version: '3.8'

services:
  job-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-scraper-api
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./data/jobs.db
      - SCRAPE_INTERVAL_HOURS=1
      - API_PORT=8001
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./models:/app/models
      - ./scrapers:/app/scrapers
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

